name: xregrid-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9,<3.14
  - esmpy
  - xesmf
  - xarray
  - cf-xarray
  - pyproj
  - numpy
  - scipy
  - dask
  - netcdf4
  - pandas
  - matplotlib
  - cartopy
  - pooch
  - pytest
  - pip
  - pip:
    - -e .
